Namespace(basedir='/mnt/home/aduivenvoorden/project/actpol/20230621_pcg_planck/planck11', draw_constr=False, test_conv=False, niter_cg=5, niter_mg=20, no_masked_prec=False, pol_mg=False, use_prec_harm=False, noise_scaling=None, no_beam=False, lmax_masked_cg=2000, write_steps=True)
Traceback (most recent call last):
  File "/mnt/home/aduivenvoorden/local/optweight/scripts/paper/planck_filter_pix.py", line 475, in <module>
    main(args.basedir, draw_constr=args.draw_constr, test_conv=args.test_conv,
  File "/mnt/home/aduivenvoorden/local/optweight/scripts/paper/planck_filter_pix.py", line 92, in main
    cov = hp.read_map(opj(maskdir, 'HFI_SkyMap_100_2048_R3.01_full.fits'), field=(4, 5, 6, 7, 8, 9))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/aduivenvoorden/.pyenv/versions/3.11.1/envs/enki/lib/python3.11/site-packages/astropy/utils/decorators.py", line 607, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/aduivenvoorden/.pyenv/versions/3.11.1/envs/enki/lib/python3.11/site-packages/healpy/fitsfunc.py", line 370, in read_map
    filename = pf.open(filename, memmap=memmap)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/home/aduivenvoorden/.pyenv/versions/3.11.1/envs/enki/lib/python3.11/site-packages/astropy/io/fits/hdu/hdulist.py", line 214, in fitsopen
    return HDUList.fromfile(
           ^^^^^^^^^^^^^^^^^
  File "/mnt/home/aduivenvoorden/.pyenv/versions/3.11.1/envs/enki/lib/python3.11/site-packages/astropy/io/fits/hdu/hdulist.py", line 482, in fromfile
    return cls._readfrom(
           ^^^^^^^^^^^^^^
  File "/mnt/home/aduivenvoorden/.pyenv/versions/3.11.1/envs/enki/lib/python3.11/site-packages/astropy/io/fits/hdu/hdulist.py", line 1170, in _readfrom
    fileobj = _File(
              ^^^^^^
  File "/mnt/home/aduivenvoorden/.pyenv/versions/3.11.1/envs/enki/lib/python3.11/site-packages/astropy/io/fits/file.py", line 218, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/mnt/home/aduivenvoorden/.pyenv/versions/3.11.1/envs/enki/lib/python3.11/site-packages/astropy/io/fits/file.py", line 636, in _open_filename
    self._file = open(self.name, IO_FITS_MODES[mode])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/adriaand/project/actpol/20201009_pcg_planck/meta/HFI_SkyMap_100_2048_R3.01_full.fits'
srun: error: worker5231: task 0: Exited with exit code 1
